// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZnXauqFpqQx5_Ah-4EQjyb5gs0hE5jY',
    appId: '1:811017695397:web:afd03a2da61e269f4d5d4c',
    messagingSenderId: '811017695397',
    projectId: 'fir-auth-3a1b6',
    authDomain: 'fir-auth-3a1b6.firebaseapp.com',
    storageBucket: 'fir-auth-3a1b6.appspot.com',
    measurementId: 'G-GM7KMVNTZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0aLpAUJqp8DmMTjDl7zxsk-8OaJ5A_SA',
    appId: '1:811017695397:android:baccbfb596e875904d5d4c',
    messagingSenderId: '811017695397',
    projectId: 'fir-auth-3a1b6',
    storageBucket: 'fir-auth-3a1b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1Sll1WofInLTdEFN2DBaWZTmNcvEaAI',
    appId: '1:811017695397:ios:85d4950f6ec71c724d5d4c',
    messagingSenderId: '811017695397',
    projectId: 'fir-auth-3a1b6',
    storageBucket: 'fir-auth-3a1b6.appspot.com',
    iosClientId: '811017695397-mu78g1vl2poeqhb0qsajjmjvisb3fnr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1Sll1WofInLTdEFN2DBaWZTmNcvEaAI',
    appId: '1:811017695397:ios:85d4950f6ec71c724d5d4c',
    messagingSenderId: '811017695397',
    projectId: 'fir-auth-3a1b6',
    storageBucket: 'fir-auth-3a1b6.appspot.com',
    iosClientId: '811017695397-mu78g1vl2poeqhb0qsajjmjvisb3fnr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
